import type { Theme } from '../tokens';

export const defaultTheme: Theme = {
  name: 'default',
  colors: {
    text: {
      primary: '#18181B',
      secondary: '#3F3F46',
      muted: '#54545B',
      faint: '#6E6E76',
      inverse: '#FFFFFF',
    },
    surface: {
      page: '#FFFFFF',
      soft: '#F6F5F2',
      paper: '#FAFAF7',
      code: '#F4F4F2',
    },
    border: {
      subtle: '#E5E4E0',
      strong: '#18181B',
      accent: '#18306E',
    },
    accent: {
      primary: '#18306E',
      soft: '#E7ECF6',
      on: '#FFFFFF',
    },
    chrome: {
      bg: '#F2F1ED',
      panel: '#FFFFFF',
      panelBorder: '#E5E4E0',
      hover: '#EDECE7',
      selected: '#E7ECF6',
      danger: '#B42318',
      success: '#067647',
      tagBg: '#EDECE7',
    },
  },
  fonts: {
    sans: '"Pretendard Variable", "Pretendard", "SUIT", "Apple SD Gothic Neo", "Noto Sans KR", -apple-system, BlinkMacSystemFont, system-ui, "Segoe UI", Roboto, sans-serif',
    mono: '"JetBrains Mono", "SF Mono", ui-monospace, Menlo, Consolas, monospace',
  },
  fontSize: {
    name: '28px',
    role: '14px',
    contact: '12.5px',
    intro: '15px',
    section: '13px',
    sectionMeta: '12px',
    project: '15px',
    stack: '12.5px',
    body: '13.5px',
    bullet: '13.5px',
    emphasis: '13.5px',
    metric: '14px',
    learning: '13.5px',
    link: '12.5px',
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  lineHeight: {
    tight: 1.25,
    snug: 1.4,
    normal: 1.55,
    body: 1.7,
    loose: 1.85,
  },
  tracking: {
    tight: '-0.01em',
    normal: '0',
    section: '0.08em',
  },
  space: {
    0: '0',
    1: '2px',
    2: '4px',
    3: '6px',
    4: '8px',
    5: '12px',
    6: '16px',
    7: '20px',
    8: '24px',
    9: '32px',
    10: '40px',
    11: '56px',
    12: '72px',
  },
  gap: {
    section: '22px',
    block: '14px',
    paragraph: '6px',
    bullet: '4px',
  },
  a4: {
    width: '794px',
    height: '1123px',
    padX: '56px',
    padY: '52px',
    contentW: '682px',
  },
  borderWidth: {
    hair: '0.5px',
    thin: '1px',
    medium: '1.5px',
  },
  radius: {
    none: '0',
    sm: '2px',
    md: '3px',
    pill: '999px',
  },
  shadow: {
    paper: '0 1px 0 rgba(24,24,27,0.04), 0 10px 30px rgba(24,24,27,0.06)',
  },
};
